### ISSUE TITLE
How to run using unitest_solution_gen.cpp

### ISSUE THREAD

**Issue by swapniel99** [wc-duck/pymmh3#2]
I am getting segmentation fault. Are there any flags used to complile?

**Comment by wc-duck** [comment]
First of all I have to ask, why do you want to run that? :) It is only used to generate the checked in "solution" files used in the unit-tests.

Other than that it seem to work here at my machine? What are you compiling it with? I just run "gcc test/unitest_solution_gen.cpp -o sgen" and then run the file with "./sgen".

Where do you get the segfault? Do you have a debugger available? I guess that it might segfault if you do not run in so that it can find the test-files at the hardcoded path "test/pg1260.txt".

**Comment by swapniel99** [comment]
Ok got it. I was actually inside test directory when compiling it.

By the way your README.md says the performance is bad. But it is true only for python.
In pypy, this beats mmh3 by about 20x speed :)
Moreover I think the code is compatible with mmh3 2.3.1
So I want to recreate the solution just to be sure.
I will send a merge request soon. :)

**Comment by wc-duck** [comment]
Ohh... thats fun to hear. I would was mostly just guessing since I haven't profiled ;) But in pypy it is kind of resonable since the code should JIT really well ( I guess again ;) ).
I'll close this issue now, just re-open this one or open a new one if you have any other questions.
