### ISSUE TITLE
Difference from mmh3

### ISSUE THREAD

**Issue by aliabbasrizvi** [wc-duck/pymmh3#4]
Hi

I was trying out pymmh3 vs mmh3 (https://pypi.python.org/pypi/mmh3/2.0) and noticed that for certain inputs the value was different. 
It seems to me that `pymmh3.hash` returns an unsigned 32 integer vs `mmh3.hash` which returns a signed 32 bit integer. Is this difference intentional?

You could try with the value 'abc' and would notice that `pymmh3.hash('abc')` returns 3017643002 whereas `mmh3.hash('abc')` returns -1277324294. The 2 differ by 4294967296 (which is 2^32) and so I am assuming that for negative values some addition is being done, but just wanted to confirm.

Thanks

**Comment by swapniel99** [comment]
Hi,

They are both the same in hexadecimal: 0xb3dd93fa

**Comment by swapniel99** [comment]
Hi,

They are both the same in hexadecimal: 0xb3dd93fa
```
>>> hex(3017643002 & 0xFFFFFFFF)
'0xb3dd93fa'
>>> hex(-1277324294 & 0xFFFFFFFF)
'0xb3dd93fa'
>>>
```

**Comment by wc-duck** [comment]
They are the same value in the lower 32 bit yes, however there is a discrepancy between mmh3 and pymmh3 and that is a bad thing since they should be replaceable =/

I really have no good Idea on how to solve the issue, but maybe pymmh3 should be changed to calculate signed-hash values instead, just for conformance.
I think that it really should return unsigned values, but if pymmh3 should claim to be interchangeable with mmh3 this need to change =/

I'll have to think about it a bit more. As @swapniel99 said, you can work around the issue by "casting" the value to unsigned with an & 0xFFFFFFFF.

**Comment by aliabbasrizvi** [comment]
Thanks for the quick turnaround @swapniel99 and @wc-duck . For now I think I can make work with @swapniel99 's suggestion. Would be great if this would conform with mmh3.

**Comment by swapniel99** [comment]
I know how to fix this.

**Comment by aliabbasrizvi** [comment]
I think this is good to close now. Thanks.
